language: go

go:
  - master

install:
  - "LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/retgits/lambda-builder/releases/latest)"
  - LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
  - ARTIFACT_URL="https://github.com/retgits/lambda-builder/releases/download/$LATEST_VERSION/lambda-builder"
  - curl -O -L $ARTIFACT_URL
  - chmod +x lambda-builder
  - pip install --user awscli
  - pip install --user aws-sam-cli
  
script:
  - pwd
  - ls -alh
  - ./lambda-builder version
  - aws --version
  - sam --version
