AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: The AWS CloudFormation template for the Trello Serverless application
Resources:
  Trello:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: trello-lambda
      Runtime: go1.x
      Tracing: Active
      Policies:
        - AmazonSSMReadOnlyAccess
      Environment:
        Variables:
          region: us-west-2
      Tags:
        version: "1.0.0"
      Description: Create a Trello card for every event
      MemorySize: 128
Outputs:
  ARN:
    Value: !GetAtt Trello.Arn
    Export:
      Name: :trello:arn
